### ISSUE TITLE
17th November 2022 - Morphir Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/morphir#118]
## Date

Thursday 17th November 2022 - 11am ET / 4pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/morphir/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Sharing Morphir project meeting calendar invite
- [x] Move from webex to zoom
- [ ] JSON Schema for IR portability
- [ ] Scala progress report and roadmap
- [ ] TypeScript API for IR processing
- [ ] AOB, Q&A & Adjourn (5mins)

### WebEx info

**Webex:**
https://finos.webex.com/finos/j.php?MTID=mc06ba4f96e798bb141883a77db0aa4e5

**Dial-in**

- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Meeting number:** 2555 504 4597

**Github Repo:** https://github.com/finos/morphir/

**Mailing List:** Email morphir+subscribe@finos.org to subscribe to our mailing list

**Comment by stephengoldbaum** [comment]
Topics for today:

1. Move from webex to zoom
2. JSON Schema for IR portability
3. Scala progress report and roadmap
4. TypeScript API for IR processing

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Hi

**Comment by DamianReeves** [comment]
Hi

**Comment by eteridvalishvili** [comment]
Eteri @FINOS

**Comment by stephengoldbaum** [comment]
# Minutes

## Morphir Elm Status

- **Morphir IR Portability** - This is an effort to enable backend development in popular languages. Our immediate goal is TypeScript, which would complement the current Elm and upcoming Scala support.

- **JSON Schema Backend** - The JSON Schema Backend generates a JSON Schema from supported types in the IR.  There are two current use cases:
   - Enabling IR Portability to other languages so that developers can use languages other than Elm to write backends
   - Generating types and data shapes that can be used within OpenAPI for defining APIs.  Attila noted that we'll look to release this sooner since it is simpler than IR Portability.

## Morphir Scala Status
- **OpenAPI frontend** - C1 has been working on OpenAPI -> Morphir compilation (via Elm). This would bring existing OpenAPI into the Morphir ecosystem, which would allow more advanced editing.
- **Scala Frontend** - Unpausing this.
- **Morphir Scala CLI** - Enabling a union of Scala and Elm command line tools by wrapping in Maven. Note that Antoine has also built a Maven wrapper for LCR, so we should align these.
- **Package Management** - Seeking to leverage the Maven infrastructure to enable package and dependency management.  This is a complex issue that overlaps the same requirements for Morphir Elm, which has been leaning on NPM.  It was deemed worthy to combine the efforts to a languages-agnostic syndication model that would allow the IR and sidecar files to be published and linked to language-specific package management for the various generated artifacts through syndication.  Some of  the thoughts on this were:
   - Package URL and (SPDX)[https://spdx.dev/] are good options
   - The Maven has powerful integrations so is also a good option

## Decisions
It was highlighted that decisions that affect the IR should be well-documented so that the different language backend APIs, features, and specifications can be kept in sync.  We will do so in the main (Morphir)[https://morphir.finos.org] repo through issues and documentation.
